//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NalogUser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class assemlyes : global::System.Configuration.ApplicationSettingsBase {
        
        private static assemlyes defaultInstance = ((assemlyes)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new assemlyes())));
        
        public static assemlyes Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Microsoft.ReportViewer.Common.dll")]
        public string MicrosoftReportViewerCommon {
            get {
                return ((string)(this["MicrosoftReportViewerCommon"]));
            }
            set {
                this["MicrosoftReportViewerCommon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Microsoft.ReportViewer.ProcessingObjectModel.dll")]
        public string MicrosoftReportViewerProcessingObjectModel {
            get {
                return ((string)(this["MicrosoftReportViewerProcessingObjectModel"]));
            }
            set {
                this["MicrosoftReportViewerProcessingObjectModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Microsoft.ReportViewer.WebForms.dll")]
        public string MicrosoftReportViewerWebForms {
            get {
                return ((string)(this["MicrosoftReportViewerWebForms"]));
            }
            set {
                this["MicrosoftReportViewerWebForms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Microsoft.ReportViewer.WinForms.dll")]
        public string MicrosoftReportViewerWinForms {
            get {
                return ((string)(this["MicrosoftReportViewerWinForms"]));
            }
            set {
                this["MicrosoftReportViewerWinForms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\PresentationCore.dll")]
        public string PresentationCore {
            get {
                return ((string)(this["PresentationCore"]));
            }
            set {
                this["PresentationCore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\PresentationFramework.dll")]
        public string PresentationFramework {
            get {
                return ((string)(this["PresentationFramework"]));
            }
            set {
                this["PresentationFramework"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\System.Data.DataSetExtensions.dll")]
        public string SystemDataDataSetExtensions {
            get {
                return ((string)(this["SystemDataDataSetExtensions"]));
            }
            set {
                this["SystemDataDataSetExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\System.Xml.Linq.dll")]
        public string SystemXmlLinq {
            get {
                return ((string)(this["SystemXmlLinq"]));
            }
            set {
                this["SystemXmlLinq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\UIAutomationProvider.dll")]
        public string UIAutomationProvider {
            get {
                return ((string)(this["UIAutomationProvider"]));
            }
            set {
                this["UIAutomationProvider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\WindowsBase.dll")]
        public string WindowsBase {
            get {
                return ((string)(this["WindowsBase"]));
            }
            set {
                this["WindowsBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\WindowsFormsIntegration.dll")]
        public string WindowsFormsIntegration {
            get {
                return ((string)(this["WindowsFormsIntegration"]));
            }
            set {
                this["WindowsFormsIntegration"] = value;
            }
        }
    }
}
