//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NalogUser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class reports : global::System.Configuration.ApplicationSettingsBase {
        
        private static reports defaultInstance = ((reports)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new reports())));
        
        public static reports Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Report_kdol_subjects.rdlc")]
        public string ReportKdolSubjects {
            get {
                return ((string)(this["ReportKdolSubjects"]));
            }
            set {
                this["ReportKdolSubjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Report_population_districts.rdlc")]
        public string ReportPopulationDistricts {
            get {
                return ((string)(this["ReportPopulationDistricts"]));
            }
            set {
                this["ReportPopulationDistricts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Report_total_ti_districts.rdlc")]
        public string ReportTotalTIDistricts {
            get {
                return ((string)(this["ReportTotalTIDistricts"]));
            }
            set {
                this["ReportTotalTIDistricts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Report_total_ti_subjects.rdlc")]
        public string ReportTotalTISubjects {
            get {
                return ((string)(this["ReportTotalTISubjects"]));
            }
            set {
                this["ReportTotalTISubjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Report_Population_Subjects.rdlc")]
        public string ReportPopulationSubjects {
            get {
                return ((string)(this["ReportPopulationSubjects"]));
            }
            set {
                this["ReportPopulationSubjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Report_ti_subjects.rdlc")]
        public string ReportViewTISubjects {
            get {
                return ((string)(this["ReportViewTISubjects"]));
            }
            set {
                this["ReportViewTISubjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Report_ti_taxes.rdlc")]
        public string ReportViewTITaxes {
            get {
                return ((string)(this["ReportViewTITaxes"]));
            }
            set {
                this["ReportViewTITaxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Report_Total_TI_Ved_Subjects.rdlc")]
        public string ReportTotalTIVedSubjects {
            get {
                return ((string)(this["ReportTotalTIVedSubjects"]));
            }
            set {
                this["ReportTotalTIVedSubjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Report_total_tax_ved_error.rdlc")]
        public string ReportViewTotalTaxVedError {
            get {
                return ((string)(this["ReportViewTotalTaxVedError"]));
            }
            set {
                this["ReportViewTotalTaxVedError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Report_total_ti_subjects_all.rdlc")]
        public string ReportTotalTISubjectsAll {
            get {
                return ((string)(this["ReportTotalTISubjectsAll"]));
            }
            set {
                this["ReportTotalTISubjectsAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Report_Kdol_Subjects_All.rdlc")]
        public string ReportKdolSubjectsAll {
            get {
                return ((string)(this["ReportKdolSubjectsAll"]));
            }
            set {
                this["ReportKdolSubjectsAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Report_total_ti_ved_subjects_all.rdlc")]
        public string ReportTotaTIVedSubjectsAll {
            get {
                return ((string)(this["ReportTotaTIVedSubjectsAll"]));
            }
            set {
                this["ReportTotaTIVedSubjectsAll"] = value;
            }
        }
    }
}
